project:
  outputs:
    dev:
      dataset: data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dbt/credentials/data-practice-348620-b8edf47bbba1.json
      location: EU
      method: service-account
      priority: interactive
      project: data-practice-348620
      threads: 1
      type: bigquery
  target: dev
